@include('siberad.dashboards.laporan-pimpinan')
@include('siberad.dashboards.partials.danpus-sidebar-submenu-cleanup')
@include('siberad.dashboards.partials.danpus-ringkasan-submenu-hide')
@include('siberad.dashboards.partials.global-shell-enhancements')
@include('siberad.dashboards.partials.danpus-monitoring-text-fix')
