<style id="admin-report-center-style">
.admin-report-center{display:none;margin-top:20px;border:1px solid var(--border-soft);border-radius:14px;background:var(--panel);box-shadow:0 10px 28px rgba(15,23,42,.07);overflow:hidden}
.admin-report-center.open{display:block}
.admin-report-tabs{display:flex;gap:10px;padding:14px 16px;border-bottom:1px solid var(--border-soft);background:var(--panel-alt);align-items:center}
.admin-report-tab{border:1px solid #FF9800;background:#FF9800;color:#111827;padding:10px 18px;border-radius:10px;font-family:var(--body);font-size:12px;font-weight:800;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;min-height:40px;box-shadow:0 4px 10px rgba(201,122,0,.14);transition:background .15s ease,border-color .15s ease,box-shadow .15s ease,transform .15s ease,color .15s ease}
.admin-report-tab:hover{background:#cd8f1d;border-color:#cd8f1d;color:#111827;box-shadow:0 5px 13px rgba(201,122,0,.18)}
.admin-report-tab:active{transform:scale(.98)}
.admin-report-tab.active{background:#FF9800;color:#111827;border-color:#FF9800;box-shadow:0 5px 14px rgba(201,122,0,.18)}
.admin-report-head{padding:17px 18px 12px;display:flex;align-items:flex-start;justify-content:space-between;gap:16px}
.admin-report-head-title h3{margin:0;font-family:var(--display);font-size:17px;font-weight:700;color:var(--text)}
.admin-report-head-title p{margin:4px 0 0;font-size:11.5px;color:var(--text-muted);line-height:1.5}
.admin-report-head-actions{display:flex;gap:8px;position:relative;flex-shrink:0}
.admin-report-download{height:36px;border-radius:9px;border:1px solid var(--gold);background:var(--gold);color:#111827;padding:0 12px;font-family:var(--body);font-size:11px;font-weight:800;cursor:pointer;display:inline-flex;align-items:center;gap:7px;box-shadow:0 5px 14px rgba(201,122,0,.14)}
.admin-report-download:hover{filter:brightness(1.03)}
.admin-report-download svg{width:15px;height:15px;stroke:currentColor;fill:none;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}
.admin-report-menu{position:absolute;top:42px;right:0;z-index:20;min-width:176px;padding:6px;border:1px solid var(--border-soft);border-radius:10px;background:var(--panel);box-shadow:0 14px 30px rgba(15,23,42,.13);display:none}
.admin-report-menu.open{display:block}
.admin-report-menu button{width:100%;border:0;background:transparent;color:var(--text);text-align:left;padding:9px 10px;border-radius:8px;font-family:var(--body);font-size:11px;cursor:pointer}
.admin-report-menu button:hover{background:var(--gold-dim);color:var(--text)}
.admin-report-filter{padding:0 18px 14px;display:flex;flex-wrap:wrap;gap:9px;align-items:center}
.admin-report-search{position:relative;flex:1 1 250px;min-width:200px}
.admin-report-search svg{position:absolute;left:11px;top:50%;transform:translateY(-50%);width:15px;height:15px;stroke:var(--text-dim);fill:none;pointer-events:none}
.admin-report-search input,.admin-report-filter input[type="date"]{width:100%;height:38px;box-sizing:border-box;border:1px solid var(--border);border-radius:9px;background:var(--panel);color:var(--text);font-family:var(--body);font-size:12px;padding:8px 11px}
.admin-report-search input{padding-left:33px}
.admin-report-filter input:focus{outline:none;border-color:var(--gold)}
.admin-report-count{font-size:10.5px;color:var(--text-dim);margin-left:auto;white-space:nowrap}
.admin-report-table-wrap{margin:0 18px 18px;border:1px solid var(--border-soft);border-radius:11px;overflow-x:auto !important;overflow-y:auto !important;background:var(--panel);height:330px;max-height:330px;min-height:330px;scrollbar-gutter:stable both-edges}
.admin-report-table{width:100%;border-collapse:collapse;min-width:740px}
.admin-report-table th{position:sticky;top:0;z-index:2;background:var(--panel-alt);color:var(--text-muted);font-family:var(--mono);font-size:9.5px;text-transform:uppercase;letter-spacing:.05em;text-align:left;padding:10px 11px;border-bottom:1px solid var(--border-soft);white-space:nowrap}
.admin-report-table td{font-family:var(--body);font-size:11.5px;color:var(--text);padding:10px 11px;border-bottom:1px solid var(--border-soft);vertical-align:top}
.admin-report-table tr:last-child td{border-bottom:0}
.admin-report-table td.muted{color:var(--text-muted)}
.admin-report-empty{padding:30px 18px;text-align:center;color:var(--text-muted);font-size:12px}
.admin-report-loading{padding:30px 18px;text-align:center;color:var(--text-muted);font-size:12px}
.admin-report-footer{padding:0 18px 18px;display:flex;justify-content:space-between;align-items:center;gap:10px;color:var(--text-dim);font-size:10px}
.admin-report-print{height:36px;padding:0 12px;border:1px solid var(--border);background:var(--panel);color:var(--text);border-radius:9px;font-family:var(--body);font-size:11px;font-weight:700;cursor:pointer}
.admin-report-print:hover{border-color:var(--gold);background:var(--gold-dim)}
@media(max-width:760px){.admin-report-tabs{gap:8px;padding:12px}.admin-report-tab{flex:0 1 auto;padding:10px 14px}.admin-report-head{flex-direction:column}.admin-report-head-actions{width:100%}.admin-report-download{flex:1}.admin-report-filter{flex-direction:column;align-items:stretch}.admin-report-count{margin-left:0}.admin-report-table-wrap{height:300px;max-height:300px;min-height:300px}.admin-report-table{min-width:680px}}
</style>
<script>
(function(){
'use strict';
if(window.__ADMIN_REPORT_CENTER__)return;window.__ADMIN_REPORT_CENTER__=true;
var ENDPOINTS={users:@json(route('admin.laporan.report-center.users')),activities:@json(route('admin.laporan.report-center.activities')),userExcel:@json(route('admin.laporan.export-pengguna')),activityExcel:@json(route('admin.laporan.export-aktivitas')),userPdf:@json(route('admin.laporan.cetak',['jenis'=>'pengguna'])),activityPdf:@json(route('admin.laporan.cetak',['jenis'=>'aktivitas']))};
function norm(v){return String(v||'').replace(/\s+/g,' ').trim().toLowerCase()}
function relevant(el){var t=norm(el.textContent);return t.includes('export pengguna')||t.includes('export aktivitas')||t.includes('cetak pengguna')||t.includes('cetak aktivitas')}
function findRoot(){var heading=[].slice.call(document.querySelectorAll('h1,h2,h3,h4,strong')).find(function(el){return norm(el.textContent)==='laporan pengguna & aktivitas'});if(!heading)return null;heading.textContent='Data Laporan';var root=heading;for(var i=0;i<8&&root;i++,root=root.parentElement){if([].slice.call(root.querySelectorAll('a,button')).filter(relevant).length>=4)return root}return heading.parentElement}
function makeMount(root){var old=document.getElementById('adminReportCenter');if(old)return old;var actions=[].slice.call(root.querySelectorAll('a,button')).filter(relevant);if(!actions.length)return null;var group=actions[0].parentElement;for(var i=0;i<5&&group&&group!==root;i++,group=group.parentElement){if([].slice.call(group.querySelectorAll('a,button')).filter(relevant).length>=4)break}if(group)group.style.display='none';var mount=document.createElement('div');mount.id='adminReportCenter';mount.className='admin-report-center open';mount.innerHTML='\n<div class="admin-report-tabs"><button class="admin-report-tab active" data-report-tab="users">Data Pengguna</button><button class="admin-report-tab" data-report-tab="activities">Aktivitas Sistem</button></div>\n<div class="admin-report-head"><div class="admin-report-head-title"><h3 id="adminReportTitle">Data Pengguna</h3><p id="adminReportSubtitle">Daftar pengguna sistem yang dapat dilihat dan diunduh.</p></div><div class="admin-report-head-actions"><button type="button" class="admin-report-download" id="adminReportDownloadBtn"><svg viewBox="0 0 24 24"><path d="M12 3v11"/><path d="m8 10 4 4 4-4"/><path d="M4 18v2h16v-2"/></svg>Unduh <span>▾</span></button><div class="admin-report-menu" id="adminReportMenu"><button type="button" data-download="excel">Excel (.xlsx)</button><button type="button" data-download="pdf">PDF / Cetak</button></div></div></div>\n<div class="admin-report-filter"><div class="admin-report-search"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input id="adminReportSearch" type="search" name="siberad_report_search_query" value="" autocomplete="new-password" autocorrect="off" autocapitalize="none" spellcheck="false" readonly inputmode="search" placeholder="Cari pengguna..."></div><input id="adminReportFrom" type="date" hidden><input id="adminReportTo" type="date" hidden><span class="admin-report-count" id="adminReportCount">Memuat data...</span></div>\n<div class="admin-report-table-wrap"><div id="adminReportBody" class="admin-report-loading">Memuat data laporan...</div></div>\n<div class="admin-report-footer"><span>Data ditampilkan langsung dari database sistem.</span><button type="button" class="admin-report-print" id="adminReportPrint">Cetak / PDF</button></div>';
root.insertAdjacentElement('beforeend',mount);return mount}
function esc(v){return String(v??'-').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
var state={kind:'users',rows:[]};
function clearReportSearch(){var search=document.getElementById('adminReportSearch');if(!search)return;search.value='';search.defaultValue='';search.setAttribute('readonly','readonly');}
function fitReportTable(){var wrap=document.querySelector('#adminReportCenter .admin-report-table-wrap');var table=wrap&&wrap.querySelector('.admin-report-table');if(!wrap||!table)return;var head=table.querySelector('thead');var rows=Array.prototype.slice.call(table.querySelectorAll('tbody tr'));if(!rows.length)return;var rowCount=Math.min(6,rows.length);var height=(head?head.getBoundingClientRect().height:0)+rows.slice(0,rowCount).reduce(function(total,row){return total+row.getBoundingClientRect().height},0)+2;var target=window.innerWidth<=760?Math.min(height,300):Math.min(height,330);wrap.style.height=target+'px';wrap.style.maxHeight=target+'px';wrap.style.minHeight=target+'px';wrap.scrollTop=0;}
function render(){var body=document.getElementById('adminReportBody');if(!body)return;var q=norm(document.getElementById('adminReportSearch').value);var rows=state.rows.filter(function(r){return !q||Object.values(r).some(function(v){return norm(v).includes(q)})});var count=document.getElementById('adminReportCount');count.textContent=rows.length.toLocaleString('id-ID')+' data ditampilkan';if(!rows.length){body.innerHTML='<div class="admin-report-empty">Tidak ada data yang cocok dengan pencarian.</div>';return}var html='';if(state.kind==='users'){html='<table class="admin-report-table"><thead><tr><th>No</th><th>Nama</th><th>Username</th><th>Email</th><th>Satuan</th><th>Jabatan</th><th>Dibuat</th></tr></thead><tbody>';rows.forEach(function(r,i){html+='<tr><td class="muted">'+(i+1)+'</td><td><strong>'+esc(r.name)+'</strong></td><td>'+esc(r.username)+'</td><td>'+esc(r.email)+'</td><td>'+esc(r.satuan)+'</td><td>'+esc(r.jabatan)+'</td><td>'+esc(r.created)+'</td></tr>'});html+='</tbody></table>'}else{html='<table class="admin-report-table"><thead><tr><th>Waktu</th><th>Pengguna</th><th>Satuan</th><th>Aksi</th><th>Deskripsi</th></tr></thead><tbody>';rows.forEach(function(r){html+='<tr><td class="muted">'+esc(r.waktu)+'</td><td><strong>'+esc(r.pengguna)+'</strong></td><td>'+esc(r.satuan)+'</td><td>'+esc(r.aksi)+'</td><td>'+esc(r.deskripsi)+'</td></tr>'});html+='</tbody></table>'}body.innerHTML=html;fitReportTable()}
function load(){var body=document.getElementById('adminReportBody'),url=state.kind==='users'?ENDPOINTS.users:ENDPOINTS.activities;body.className='admin-report-loading';body.textContent='Memuat data laporan...';var params=new URLSearchParams();if(state.kind==='activities'){var f=document.getElementById('adminReportFrom').value,t=document.getElementById('adminReportTo').value;if(f)params.set('dari',f);if(t)params.set('sampai',t)}fetch(url+'?'+params.toString(),{headers:{Accept:'application/json'}}).then(function(r){if(!r.ok)throw new Error('Gagal memuat data');return r.json()}).then(function(data){state.rows=data.rows||[];body.className='';render()}).catch(function(){body.className='admin-report-empty';body.textContent='Data laporan gagal dimuat. Silakan coba lagi.'})}
function switchTab(kind,mount){state.kind=kind;clearReportSearch();document.querySelectorAll('#adminReportCenter .admin-report-tab').forEach(function(btn){btn.classList.toggle('active',btn.dataset.reportTab===kind)});var title=document.getElementById('adminReportTitle'),sub=document.getElementById('adminReportSubtitle'),search=document.getElementById('adminReportSearch'),from=document.getElementById('adminReportFrom'),to=document.getElementById('adminReportTo');if(kind==='users'){title.textContent='Data Pengguna';sub.textContent='Daftar pengguna sistem yang dapat dilihat dan diunduh.';search.placeholder='Cari pengguna...';from.hidden=true;to.hidden=true}else{title.textContent='Aktivitas Sistem';sub.textContent='Riwayat aktivitas pengguna dan perubahan yang tercatat di sistem.';search.placeholder='Cari aktivitas, pengguna, atau aksi...';from.hidden=false;to.hidden=false}document.getElementById('adminReportMenu').classList.remove('open');load()}
function bind(mount){var search=document.getElementById('adminReportSearch');if(search){clearReportSearch();search.addEventListener('pointerdown',function(){search.removeAttribute('readonly');search.value='';});search.addEventListener('focus',function(){if(search.readOnly)search.removeAttribute('readonly');if(search.value==='admin')search.value='';render();});search.addEventListener('input',render)}['adminReportFrom','adminReportTo'].forEach(function(id){document.getElementById(id).addEventListener('change',load)});mount.querySelectorAll('[data-report-tab]').forEach(function(btn){btn.onclick=function(){switchTab(btn.dataset.reportTab,mount)}});document.getElementById('adminReportDownloadBtn').onclick=function(e){e.stopPropagation();document.getElementById('adminReportMenu').classList.toggle('open')};document.addEventListener('click',function(){document.getElementById('adminReportMenu').classList.remove('open')});mount.querySelectorAll('[data-download]').forEach(function(btn){btn.onclick=function(){var pdf=btn.dataset.download==='pdf';var url=state.kind==='users'?(pdf?ENDPOINTS.userPdf:ENDPOINTS.userExcel):(pdf?ENDPOINTS.activityPdf:ENDPOINTS.activityExcel);window.open(url,'_blank','noopener')}});document.getElementById('adminReportPrint').onclick=function(){var url=state.kind==='users'?ENDPOINTS.userPdf:ENDPOINTS.activityPdf;window.open(url,'_blank','noopener')}}
function init(){var root=findRoot();if(!root)return null;var mount=makeMount(root);if(!mount||mount.dataset.bound)return mount;mount.dataset.bound='1';bind(mount);clearReportSearch();load();return mount}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.addEventListener('pageshow',clearReportSearch);window.addEventListener('load',function(){clearReportSearch();setTimeout(clearReportSearch,100);setTimeout(clearReportSearch,500);});window.addEventListener('resize',function(){fitReportTable()});var obs=new MutationObserver(function(){init()});obs.observe(document.body,{childList:true,subtree:true});setTimeout(function(){obs.disconnect()},12000)
})();
</script>
