<style>
#permintaan-laporan .danpus-archive-actions{display:inline-flex;align-items:center;justify-content:flex-end;gap:8px;flex:0 0 auto}
#permintaan-laporan .danpus-archive-toggle{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:36px;padding:8px 13px;border:1px solid var(--p-border);border-radius:8px;background:var(--p-surface);color:var(--p-text);font:inherit;font-size:11px;font-weight:800;cursor:pointer;transition:background .15s ease,border-color .15s ease,color .15s ease,box-shadow .15s ease}
#permintaan-laporan .danpus-archive-toggle:hover{border-color:var(--p-accent);background:var(--p-surface-2)}
#permintaan-laporan .danpus-archive-toggle.is-active{background:var(--gold-solid-bright,#c97a00);border-color:var(--gold-solid-bright,#c97a00);color:var(--on-gold,#fff);box-shadow:0 7px 18px -9px rgba(201,122,0,.75)}
#permintaan-laporan .danpus-archive-toggle.is-busy{opacity:.72;pointer-events:none}
#permintaan-laporan .danpus-archive-count{display:none;align-items:center;justify-content:center;min-width:22px;height:22px;padding:0 7px;border-radius:999px;background:var(--gold-dim);border:1px solid var(--border);color:var(--gold-bright);font-family:var(--mono);font-size:10px;font-weight:800}
#permintaan-laporan .danpus-archive-count.is-visible{display:inline-flex}
#permintaan-laporan .danpus-archive-head-cell,#permintaan-laporan .danpus-archive-row-cell,#permintaan-laporan .danpus-archive-row-content{display:contents}
#permintaan-laporan .danpus-archive-checkbox{width:13px;height:13px;flex:0 0 13px;margin:0;padding:0;accent-color:var(--gold-solid-bright,#c97a00);cursor:pointer}
#permintaan-laporan.danpus-archive-mode .request-table thead tr th:first-child,#permintaan-laporan.danpus-archive-mode .request-table tbody tr td:first-child{position:relative}
#permintaan-laporan.danpus-archive-mode .danpus-archive-select-all,#permintaan-laporan.danpus-archive-mode .danpus-archive-row-checkbox{position:absolute;left:4px;top:50%;transform:translateY(-50%);z-index:2}
#permintaan-laporan .request-table tbody tr.danpus-archive-selected td{background:color-mix(in srgb,var(--gold-solid-bright,#c97a00) 5%,transparent)}
#permintaan-laporan .request-table tbody tr.danpus-archive-selected td:first-child{box-shadow:none}
</style>
<script>
(function(){
'use strict';
function initDanpusArchiveMode(){
 const panel=document.getElementById('permintaan-laporan');if(!panel||panel.dataset.danpusArchiveModeBound==='1')return;
 const head=panel.querySelector('.request-head'),table=panel.querySelector('.request-table'),tbody=table?.querySelector('tbody');if(!head||!table||!tbody)return;
 panel.dataset.danpusArchiveModeBound='1';let active=false,busy=false,refreshQueued=false;const selectedIds=new Set();
 const archiveEndpoint='{{ route('permintaan-laporan.store') }}';const historyEndpoint='{{ route('permintaan-laporan.realtime') }}?history=1&_=';
 const eligibleStatus=status=>{const n=String(status||'').replace(/\s+/g,' ').trim().toLowerCase();return n==='terlambat'||n==='dibatalkan'||n==='selesai · disetujui'||n==='selesai · ditolak'};
 const rowStatus=row=>row?.dataset?.status||'';const rowId=row=>String(row?.querySelector('[data-permintaan-id]')?.dataset?.permintaanId||'');const eligibleRows=()=>Array.from(tbody.querySelectorAll('tr[data-status]')).filter(r=>eligibleStatus(rowStatus(r)));
 const createButton=head.querySelector('#danpusOpenRequestForm');if(!createButton)return;let actions=head.querySelector('.danpus-archive-actions');
 if(!actions){actions=document.createElement('div');actions.className='danpus-archive-actions';createButton.parentNode?.insertBefore(actions,createButton);actions.appendChild(createButton)}
 const archiveButton=document.createElement('button');archiveButton.type='button';archiveButton.className='danpus-archive-toggle';archiveButton.id='danpusArchiveToggle';archiveButton.setAttribute('aria-pressed','false');archiveButton.title='Mode Arsip / Arsipkan permintaan terpilih';
 archiveButton.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 6.5h14v12H5z"></path><path d="M4 6.5h16"></path><path d="M8 4h8l1 2.5H7L8 4z"></path><path d="M9 11.5h6"></path></svg><span>Arsip</span>';actions.insertBefore(archiveButton,createButton);
 const countBadge=document.createElement('span');countBadge.className='danpus-archive-count';countBadge.id='danpusArchiveSelectedCount';countBadge.setAttribute('aria-live','polite');countBadge.textContent='0';actions.insertBefore(countBadge,archiveButton);
 function csrf(){return document.querySelector('input[name="_token"]')?.value||document.querySelector('meta[name="csrf-token"]')?.content||''}
 function historyBodies(){return Array.from(document.querySelectorAll('#riwayat .dtbl tbody,#riwayat .clean-table tbody,#status .clean-table tbody,#status .dtbl tbody')).filter(Boolean)}
 function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function renderArchivedItem(tb,item){
   const key='archive-'+item.id;if(tb.querySelector('[data-archive-key="'+key+'"]'))return;
   tb.querySelectorAll('tr').forEach(r=>{if(r.querySelector('.empty-state'))r.remove()});
   const t=tb.closest('table');const headers=Array.from(t?.querySelectorAll('thead th')||[]).map(h=>h.textContent.trim().toLowerCase());
   const isStatus=headers.includes('satlak')&&headers.includes('perihal')&&headers.includes('tujuan')&&headers.includes('status');
   const tr=document.createElement('tr');tr.dataset.archiveKey=key;tr.dataset.search=(String(item.perihal||'')+' '+String(item.tujuan_nama||'')).toLowerCase();
   if(isStatus){tr.innerHTML='<td style="text-align:center"><span class="satuan-pill">DANPUS</span></td><td class="subject">'+esc(item.perihal||'-')+'<div class="muted">Arsip permintaan laporan</div></td><td style="text-align:center"><span class="satuan-pill">'+esc(item.tujuan||item.tujuan_nama||'-')+'</span></td><td style="text-align:center"><span class="status-pill '+archiveStatusClass(item.status)+'">'+esc(item.status||'Arsip')+'</span></td><td style="text-align:center">'+esc(item.archived_at||'-')+'</td><td style="text-align:center"><button type="button" class="detail-btn archive-detail-btn" data-perihal="'+esc(item.perihal)+'" data-tujuan="'+esc(item.tujuan_nama||'-')+'" data-prioritas="'+esc(item.prioritas||'-')+'" data-tanggal="'+esc(item.archived_at||'-')+'">Lihat</button></td>'}
   else{tr.innerHTML='<td>'+esc(item.perihal||'-')+'<div class="muted">Arsip permintaan laporan</div></td><td style="text-align:center"><span class="satuan-pill">'+esc(item.tujuan||item.tujuan_nama||'-')+'</span></td><td>'+esc(item.prioritas||'-')+'</td><td style="text-align:center"><span class="status-dot amber">'+esc(item.status||'Arsip')+'</span></td><td style="text-align:center">'+esc(item.archived_at||'-')+'</td><td style="text-align:center"><button type="button" class="detail-btn archive-detail-btn" data-perihal="'+esc(item.perihal)+'" data-tujuan="'+esc(item.tujuan_nama||'-')+'" data-prioritas="'+esc(item.prioritas||'-')+'" data-tanggal="'+esc(item.archived_at||'-')+'">Detail</button></td>'}
   tb.prepend(tr);
 }
 function archiveStatusClass(status){const n=String(status||'').toLowerCase();if(n.includes('setuj'))return'ok';if(n.includes('tolak')||n.includes('batal')||n.includes('terlambat'))return'bad';return'wait'}
 function syncHistory(items){historyBodies().forEach(tb=>items.forEach(item=>renderArchivedItem(tb,item)))}
 async function loadHistory(){try{const r=await fetch(historyEndpoint+Date.now(),{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest'}});if(!r.ok)return;const data=await r.json();const items=Array.isArray(data.items)?data.items:[];syncHistory(items);removeArchivedRows(items.map(i=>i.id));}catch(e){}}
 function removeArchivedRows(ids){const set=new Set((ids||[]).map(String));Array.from(tbody.querySelectorAll('tr[data-status]')).forEach(row=>{if(set.has(rowId(row)))row.remove()});selectedIds.forEach(id=>{if(set.has(String(id)))selectedIds.delete(id)});syncRows()}
 function ensureHeaderCheckbox(){const th=table.querySelector('thead tr th:first-child');if(!th)return null;let wrap=th.querySelector('.danpus-archive-head-cell');if(!wrap){const label=document.createElement('span');label.className='danpus-archive-head-label';while(th.firstChild)label.appendChild(th.firstChild);wrap=document.createElement('span');wrap.className='danpus-archive-head-cell';wrap.appendChild(label);th.appendChild(wrap)}let cb=wrap.querySelector('.danpus-archive-select-all');if(!cb){cb=document.createElement('input');cb.type='checkbox';cb.className='danpus-archive-checkbox danpus-archive-select-all';cb.setAttribute('aria-label','Pilih semua baris yang dapat diarsipkan');wrap.insertBefore(cb,wrap.firstChild);cb.addEventListener('change',()=>{eligibleRows().forEach(row=>{const id=rowId(row);if(!id)return;cb.checked?selectedIds.add(id):selectedIds.delete(id)});syncRows();syncHeaderCheckbox()})}return cb}
 function ensureRowCheckbox(row){const td=row.querySelector('td:first-child');if(!td)return null;let wrap=td.querySelector('.danpus-archive-row-cell');if(!wrap){const content=document.createElement('span');content.className='danpus-archive-row-content';while(td.firstChild)content.appendChild(td.firstChild);wrap=document.createElement('span');wrap.className='danpus-archive-row-cell';wrap.appendChild(content);td.appendChild(wrap)}let cb=wrap.querySelector('.danpus-archive-row-checkbox');if(!cb){cb=document.createElement('input');cb.type='checkbox';cb.className='danpus-archive-checkbox danpus-archive-row-checkbox';cb.setAttribute('aria-label','Pilih permintaan laporan ini untuk diarsipkan');const id=rowId(row);cb.dataset.permintaanId=id;wrap.insertBefore(cb,wrap.firstChild);cb.addEventListener('click',e=>e.stopPropagation());cb.addEventListener('change',()=>{if(id)(cb.checked?selectedIds.add(id):selectedIds.delete(id));row.classList.toggle('danpus-archive-selected',cb.checked);syncHeaderCheckbox();syncCount()})}return cb}
 function removeRowArchiveUI(row){row.classList.remove('danpus-archive-eligible-row','danpus-archive-selected');const wrap=row.querySelector('.danpus-archive-row-cell');if(!wrap)return;const content=wrap.querySelector('.danpus-archive-row-content'),td=row.querySelector('td:first-child');if(content&&td)while(content.firstChild)td.appendChild(content.firstChild);wrap.remove()}
 function removeHeaderArchiveUI(){const wrap=table.querySelector('thead tr th:first-child .danpus-archive-head-cell');if(!wrap)return;const label=wrap.querySelector('.danpus-archive-head-label'),th=wrap.closest('th');if(label&&th)while(label.firstChild)th.appendChild(label.firstChild);wrap.remove()}
 function syncRows(){Array.from(tbody.querySelectorAll('tr[data-status]')).forEach(row=>{if(!active||!eligibleStatus(rowStatus(row))){removeRowArchiveUI(row);return}row.classList.add('danpus-archive-eligible-row');const cb=ensureRowCheckbox(row),id=rowId(row);if(cb){cb.checked=!!(id&&selectedIds.has(id));row.classList.toggle('danpus-archive-selected',cb.checked)}});if(active)ensureHeaderCheckbox();else removeHeaderArchiveUI();syncHeaderCheckbox();syncCount()}
 function syncHeaderCheckbox(){const cb=table.querySelector('thead .danpus-archive-select-all');if(!cb)return;const boxes=eligibleRows().map(r=>r.querySelector('.danpus-archive-row-checkbox')).filter(Boolean);const all=boxes.length>0&&boxes.every(b=>b.checked);cb.checked=all;cb.indeterminate=!all&&boxes.some(b=>b.checked);cb.disabled=boxes.length===0}
 function syncCount(){for(const id of Array.from(selectedIds))if(!eligibleRows().some(r=>rowId(r)===id))selectedIds.delete(id);countBadge.textContent=String(selectedIds.size);countBadge.classList.toggle('is-visible',active&&selectedIds.size>0)}
 function setMode(next){active=!!next;panel.classList.toggle('danpus-archive-mode',active);archiveButton.classList.toggle('is-active',active);archiveButton.setAttribute('aria-pressed',active?'true':'false');if(!active)selectedIds.clear();syncRows()}
 async function archiveSelected(){if(busy||selectedIds.size===0)return;busy=true;archiveButton.classList.add('is-busy');try{const form=new FormData();form.append('archive_mode','1');selectedIds.forEach(id=>form.append('permintaan_laporan_ids[]',id));const token=csrf();const r=await fetch(archiveEndpoint,{method:'POST',credentials:'same-origin',body:form,headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest',...(token?{'X-CSRF-TOKEN':token}:{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||'Permintaan gagal diarsipkan.');const items=Array.isArray(data.items)?data.items:[];syncHistory(items);removeArchivedRows(data.archived_ids||items.map(i=>i.id));selectedIds.clear();setMode(false);window.siberadShowToast?.('success',data.message||'Permintaan berhasil dipindahkan ke Riwayat Laporan.')}catch(error){window.siberadShowToast?.('error',error.message||'Permintaan gagal diarsipkan.')}finally{busy=false;archiveButton.classList.remove('is-busy');syncRows()}}
 archiveButton.addEventListener('click',()=>{if(active&&selectedIds.size>0){archiveSelected();return}setMode(!active)});
 document.addEventListener('click',e=>{const btn=e.target.closest('.archive-detail-btn');if(!btn||!window.openReportDetail)return;const b=document.createElement('button');b.dataset.pengirim='DANPUS';b.dataset.tujuan=btn.dataset.tujuan||'-';b.dataset.perihal=btn.dataset.perihal||'-';b.dataset.prioritas=btn.dataset.prioritas||'-';b.dataset.progres='-';b.dataset.proyek='Arsip permintaan laporan';b.dataset.tanggal=btn.dataset.tanggal||'-';b.dataset.deskripsi='Permintaan laporan yang telah dipindahkan ke Riwayat Laporan.';b.dataset.readonly='1';b.dataset.readonlyText='Data arsip hanya untuk melihat.';window.openReportDetail(b)});
 const scheduleRefresh=()=>{if(refreshQueued)return;refreshQueued=true;requestAnimationFrame(()=>{refreshQueued=false;syncRows()})};new MutationObserver(scheduleRefresh).observe(tbody,{childList:true,subtree:true});syncRows();loadHistory();window.setInterval(()=>{if(!document.hidden&&!busy)loadHistory()},5000)
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initDanpusArchiveMode,{once:true});else initDanpusArchiveMode();
})();
</script>