@php
// Status & tombol aksi di tab ini sengaja lebih spesifik dari checkpoint
// polos "Sedang diproses" di Log Aktivitas -- pimpinan perlu sinyal kapan
// harus bertindak (Menunggu), dan kapan laporan lagi diulang satuan
// (Revisi) setelah pimpinan klik tombol Revisi dari baris Selesai·Ditolak.
// Status Laporan/PermintaanLaporan tidak punya kolom pembeda "asal Revisi",
// jadi dideteksi dari laporan TERAKHIR yang nempel ke permintaan ini.
$laporanTerakhir=$item->laporans->sortByDesc('id')->first();
$sedangRevisi=$item->status===\App\Models\PermintaanLaporan::STATUS_DIKERJAKAN
    && $laporanTerakhir
    && str_contains(strtolower($laporanTerakhir->status),'revisi');
if($item->status===\App\Models\PermintaanLaporan::STATUS_DIBATALKAN){$statusPimpinan='Dibatalkan';$statusPimpinanClass='bad';}
elseif($item->status===\App\Models\PermintaanLaporan::STATUS_PEMERIKSAAN){$statusPimpinan='Menunggu';$statusPimpinanClass='blue';}
elseif($item->status===\App\Models\PermintaanLaporan::STATUS_SELESAI){
    $hasilAkhir=strtolower($item->laporan->status??'');
    if(str_contains($hasilAkhir,'tolak')){$statusPimpinan='Selesai · Ditolak';$statusPimpinanClass='bad';}
    else{$statusPimpinan='Selesai · Disetujui';$statusPimpinanClass='ok';}
}elseif($sedangRevisi){$statusPimpinan='Revisi';$statusPimpinanClass='revisi';}
elseif($item->isTerlambat()){$statusPimpinan='Terlambat';$statusPimpinanClass='bad';}
else{$statusPimpinan='Sedang diproses';$statusPimpinanClass='proses';}
$bisaEditDeadline=$item->isDapatEditDeadline();
$alasanTidakBisaEdit=$bisaEditDeadline?'':$item->alasanTidakBisaEditDeadline();
@endphp<tr class="request-row" data-permintaan-id="{{ $item->id }}" data-search="{{ strtolower($item->perihal.' '.($item->instruksi ?? '').' '.($item->tujuanSatuan->nama ?? '').' '.($item->tujuanSatuan->kode ?? '')) }}" data-status="{{ $statusPimpinan }}" onclick="danpusToggleTaskRow(this,event)"><td><span class="request-row-caret" aria-hidden="true">▸</span><span class="satuan-pill">{{ $item->tujuanSatuan->kode ?? $item->tujuanSatuan->nama ?? '-' }}</span></td><td><div class="request-subject">{{ $item->perihal }}</div>@if($item->instruksi)<div class="request-muted">{{ \Illuminate\Support\Str::limit($item->instruksi,90) }}</div>@endif</td><td><span class="priority-tag prio-{{ strtolower($item->prioritas) }}">{{ $item->prioritas }}</span></td><td><div class="request-deadline" @if(in_array($statusPimpinan,['Menunggu','Revisi'],true)) style="text-decoration:line-through;opacity:.6" @endif><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 3"/></svg>{{ $item->deadline_at?->format('d M Y, H:i')??'-' }}</div><div class="request-muted"><span class="status-pill {{ $statusPimpinanClass }}">{{ $statusPimpinan }}</span></div></td><td><div style="display:flex;align-items:center;justify-content:center;gap:7px;flex-wrap:wrap"><div class="action-row" style="display:contents"><button type="button" class="detail-btn" onclick="danpusLihatAktivitas(this)" data-satuan-id="{{ $item->tujuan_satuan_id }}" data-permintaan-id="{{ $item->id }}">Lihat</button>@if($statusPimpinan==='Dibatalkan' || $statusPimpinan==='Terlambat')<button type="button" class="detail-btn btn-edit-permintaan" onclick="bukaEditDeadlinePermintaan(this)" data-permintaan-id="{{ $item->id }}" data-perihal="{{ e($item->perihal) }}" data-deadline="{{ $item->deadline_at?->format('Y-m-d\TH:i') }}" data-editable="{{ $bisaEditDeadline ? '1' : '0' }}" data-alasan="{{ e($alasanTidakBisaEdit) }}">Edit</button>
@elseif($statusPimpinan==='Sedang diproses')<button type="button" class="detail-btn btn-batalkan-permintaan" onclick="bukaBatalkanPermintaan(this)" data-permintaan-id="{{ $item->id }}" data-perihal="{{ e($item->perihal) }}">Batal</button>
@endif</div>@if($statusPimpinan==='Menunggu')<button type="button" class="detail-btn" onclick="openReportDetail(this)" data-pengirim="{{ e($item->tujuanSatuan->nama ?? '-') }}" data-tujuan="{{ e($satuan->nama) }}" data-perihal="{{ e($item->laporan->perihal ?? $item->perihal) }}" data-prioritas="{{ e($item->laporan->prioritas ?? $item->prioritas) }}" data-progres="{{ $item->laporan->progres ?? 100 }}" data-kendala="{{ e($item->laporan->kendala ?? '') }}" data-proyek="{{ e($item->laporan->proyek ?? '-') }}" data-tanggal="{{ e($item->laporan?->created_at?->translatedFormat('d M Y H:i')) }}" data-deskripsi="{{ e($item->laporan->deskripsi ?? '') }}" data-lampiran="{{ $item->laporan?->lampiran_path ? e(asset('storage/'.$item->laporan->lampiran_path)) : '' }}" data-pimpinan-review="1" data-laporan-id="{{ $item->laporan_id }}">Detail</button>@endif @if($statusPimpinan==='Selesai · Ditolak')<button type="button" class="detail-btn btn-revisi-permintaan" onclick="bukaRevisiLaporanPimpinan(this)" data-laporan-id="{{ $item->laporan_id }}">Revisi</button>@endif</div></td></tr><tr class="request-task-row rpt-filter-detail-row" data-permintaan-id="{{ $item->id }}" hidden><td colspan="5"><div class="request-task-track">@php $rtActive = false; @endphp@forelse($item->tasks as $task)@php
    $rtState = $task->selesai ? 'done' : ($rtActive ? 'pending' : 'active');
    if (!$task->selesai) { $rtActive = true; }
    $rtTitle = $task->deskripsi.($task->selesai_at ? ' · Selesai '.$task->selesai_at->translatedFormat('d M Y H:i') : '');
    $rtLaporan = $task->laporans->sortByDesc('id')->first();
@endphp<div class="request-task-step {{ $rtState }} {{ $rtLaporan ? 'clickable' : '' }}" title="{{ $rtTitle }}" @if($rtLaporan) role="button" tabindex="0" onclick="openReportDetail(this)" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();openReportDetail(this)}" data-pengirim="{{ e($item->tujuanSatuan->nama ?? '-') }}" data-tujuan="{{ e($satuan->nama) }}" data-perihal="{{ e($rtLaporan->perihal) }}" data-prioritas="{{ e($rtLaporan->prioritas) }}" data-progres="{{ $rtLaporan->progres }}" data-kendala="{{ e($rtLaporan->kendala ?? '') }}" data-proyek="{{ e($rtLaporan->proyek ?? '-') }}" data-tanggal="{{ e($rtLaporan->created_at?->translatedFormat('d M Y H:i')) }}" data-deskripsi="{{ e($rtLaporan->deskripsi) }}" data-lampiran="{{ $rtLaporan->lampiran_path ? e(asset('storage/'.$rtLaporan->lampiran_path)) : '' }}" data-readonly="1" @endif><span class="request-task-num">{{ $task->selesai ? '✓' : $loop->iteration }}</span><span class="request-task-label">{{ $task->deskripsi }}</span></div>@empty<div class="request-muted">Tidak ada task untuk permintaan ini.</div>@endforelse</div></td></tr>
